<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="display-2 text-center mb-3">Editar categoria</h2>
		</div>
	</div>
	<div class="row">
		<div class="col">
		<form action="<?php echo APP_URL."categorias/editar"; ?>" method="POST" accept-charset="utf-8">
			<input type="hidden" name="id" value="<?php echo $this->categorias["id"]; ?>">
			
			<div class="col-6 input-group mb-3 offset-3">
				<div class="input-group-prepend">
					<span class="input-group-text">Nombre</span>
				</div>
				<input type="text" name="nombre" value="<?php echo $this->categorias["nombre"]; ?>" class="form-control">
			</div>

		<div class="col-md-12">
			<div class="row justify-content-center">
				<div class="col-md-4">
					<button type="submit" class="btn btn-success btn-block">Guardar cambios</button>
				</div>
			</div>
		</div>
	</form>
	</div>
</div>