<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="display-2 text-center">Categorias</h2>
			<a href="<?php echo APP_URL. "tareas/index"; ?>" class="btn btn-outline-warning mb-3">Regresar a tareas</a>
			<a href="<?php echo APP_URL. "categorias/agregar"; ?>" class="btn btn-outline-success mb-3">Agregar categoria</a>

			<table border="1" class="table table-dark table-responsive-lg text-center">
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Acción</th>
				</tr>
				<?php foreach ($this->categorias as $categoria): ?>
				<tr>
					<td><?php echo $categoria["id"]; ?></td>
					<td><?php echo $categoria["nombre"]; ?></td>
					<td><a href="<?php echo APP_URL. "categorias/editar/". $categoria["id"]; ?>" class="btn btn-primary mr-3 mb-1 mt-1">Editar</a><a href="<?php echo APP_URL. "categorias/eliminar/". $categoria["id"]; ?>" class="btn btn-danger mr-3 mb-1 mt-1 confirmation">Eliminar</a>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
</div>